= Ansible

Ansible automates system administration tasks.  In Ansible, **a play is a list of tasks to be executed on a set of hosts**.  The tasks can be chosen from the available modules. One or several plays are organized in a playbook. 

The tasks in a play are executed sequentially. Handlers are tasks which are triggered by ”normal” tasks and are executed only once at the end of the play which triggered the handler.

The tasks are done by modules. You will learn how to use these modules, which arguments are required and which are optional to each module and how these modules are packed together to playbooks.

Ansible can be used in two methodes:

* the **ad hoc method** by using individual modules
* the **playbook method** by combining modules in one or more plays 

So a play is an ordered set of tasks executed against hosts. These managed or targetted hosts of the play can be on premise or in the cloud.  All you need to be able to manage a system with Ansible, is ssh access.

== Study material

Read the introduction on Ansible on https://docs.ansible.com/ansible/latest/user_guide/quickstart.html[this] site. 

Watch the following videos from https://sysadmincasts.com:

* https://sysadmincasts.com/episodes/43-19-minutes-with-ansible-part-1-4[video 1]
* https://sysadmincasts.com/episodes/45-learning-ansible-with-vagrant-part-2-4[Video 2]

Do 1 to 5 in https://www.learnitguide.net/2018/06/ansible-tutorial-for-beginners-online.html[this text] and read to finish this https://linuxhint.com/ansible-tutorial-beginners/[text].

== Setting up the environment

* Make a Vagrant multimachine configuration with three machines: one master node named *master* (generic/freebsd12) and two slave nodes (generic/debian10) named *slave1* and *slave2*.

    Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
        master.vm.box = "generic/freebsd12"
        master.vm.hostname= "master"
    end
    config.vm.define "node1" do |node1|
        node1.vm.box = "generic/debian10"
        node1.vm.hostname= "node1"
    end
    config.vm.define "node2" do |node2|
        node2.vm.box = "generic/debian10"
        node2.vm.hostname= "node2"
    end
    config.vm.provider "vmware_desktop" do |vb|
        vb.gui = true
        vb.memory = "512"
    end
    end

* Install ansible on the master node

  $ su - (you will be prompted for the root password, normally vagrant)
  # pkg update
  # pkg install py37-ansible sshpass

* Verify if ansible is installed

  $ ansible --version
  $ ansible-playbook --version

* You need to specify an inventory of hosts ansible will use to run ad-hoc commands or playbooks on. The inventory file can contain the DNS names or the IP addresses of the hosts. Because DNS is not configured in this exercise, IP addresses will be used
** Modify your Vagrant file so the master machine has IP 10.10.10.10, node1 has IP 10.10.10.20 and node2 has IP 10.10.10.21.

    Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
        master.vm.box = "generic/freebsd12"
        master.vm.hostname= "master"
        master.vm.network "private_network", ip: "10.10.10.10"
    end
    config.vm.define "node1" do |node1|
        node1.vm.box = "generic/debian10"
        node1.vm.hostname= "node1"
        node1.vm.network "private_network", ip: "10.10.10.20"
    end
    config.vm.define "node2" do |node2|
        node2.vm.box = "generic/debian10"
        node2.vm.hostname= "node2"
        node2.vm.network "private_network", ip: "10.10.10.21"
    end
    config.vm.provider "vmware_desktop" do |vb|
        vb.gui = true
        vb.memory = "512"
    end
    end


* Make a subdirectory *ansible* on the master node and create a file *inventory* within the newly created directory
  
  $ cd /home/vagrant
  $ mkdir ansible
  $ cd ansible
  $ touch inventory

* Read the https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups[documentation] on Ansible inventory files and create a static inventory file in YAML format containing the IP addresses of the three machines

  all:
    hosts:
      10.10.10.10:
    children:
      nodes:
        hosts:
          10.10.10.20:
          10.10.10.21:

** Verify the listed hosts
  
  $ ansible --list-hosts -i inventory all
  $ ansible --list-hosts -i inventory ungrouped
  $ ansible --list-hosts -i inventory nodes
  $ ansible --list-hosts -i inventory nodes,ungrouped
  $ ansible-inventory -i inventory  --list

* Use ssh to connect to the two node1 and node2 machines in order to verify the ssh connection is working (Type **yes** to continue if SSH asks you something)

* Use the Ping-module to "ping" the hosts using the following command: `ansible -i inventory nodes -m ping --ask-pass`
** Use the man pages of the ansible command to figure the command out

* Switch in the previous command the ping module with the setup module and read the output

== Ansible ad hoc commands

Ad hoc commands are one-liners designed to achieve a very specific task. To put simply, Ansible ad hoc commands are one-liner Linux shell commands and playbooks are like a shell script, a collective of many commands with logic.

Ansible ad hoc commands come in handy when you want to perform a quick task.

Modules do the ”real” work in Ansible. Ansible contains a lot of modules by default, but you can also write your own.

The default syntax for using an Ansible module is: `ansible -i inventory-file host-group -m module-name -a module-arguments`
  
If you don’t know how to use the module or which arguments are optional or required, you can use the command `ansible-doc -l` for an overview of all available modules on the system and `ansible-doc *module-name*` for specific module details.

//To run an *ad hoc command*, the command must have the following syntax:
//    ansible -i inventory-file <host-pattern> [options]
//
// For example, this command should be written as follows:
//    ansible -i inventroy-file webservers -m <modulename> -a <arguments to the module>

* Write an ansible ad hoc command to check the uptime on node 1 and 2

    ansible -i inventory nodes -m shell -a uptime -k

* Sometimes it is necessary to become "root" during the installation or configuration of the system. Execute the following commands and explain their working:

  ansible -i inventory nodes -m shell -a id -k
  ansible -i inventory nodes -m shell -a id -k -b
  ansible -i inventory nodes -m shell -a id -k -b -K

* Create a UNIX user using the ansible *user module*

  ansible -i inventory nodes -m user -a "name=student1 createhome=yes" -k -b -K

  * You can obtain a list of available modules using `ansible-doc -l`
  ** How many modules are include? 

  * Use ansible-doc to figure out how to use the copy module: `ansible-doc copy`

* Try the following commands:

  `ansible -i inventory nodes -m command -a ’echo "JAJA" >> /tmp/JAJA’`
  `ansible -i inventory nodes -m shell -a ’echo "JAJA" >> /tmp/JAJA’`
  
** Explain and TEST the difference in behaviour between the two commands.
*** Tip: https://blog.confirm.ch/ansible-modules-shell-vs-command/

* Execute the following command `ansible -i inventory nodes -m copy -a 'src=/etc/passwd dest=/tmp/passwd'` twice.
** Do you see a difference in the ansible outcome?

* Use the appropriate package management module to reassure that the latest openssl version is present on the node systems

 ansible -i inventory nodes -m package -a 'name=openssl state=latest'

.NOTE
  Modules  are  ‘idempotent’,  meaning  if  you  run  them  again,  they  will  make  only the  changes  they  must  in  order  to  bring  the  system  to  the  desired  state.   This makes it very safe to rerun the same modules and playbook multiple times.  They won’t change things unless they have to change things.
  The command and shell modules will typically rerun the same command again, which is totally ok if the command is something like chmod or chown, etc. Though there is a creates flag available which can be used to make also these modules idempotent.  Test these modules with the create flag and make them ‘idempotent’ in your use.  

== Ansible Playbooks

Another  way  to  run  Ansible  is  by  using  Playbooks,  in  playbook-mode.   A  playbookby  itself  is  a  plain-text  YAML  file  that  describes  the  desired  end  state. 

**Playbooks contain plays, plays contain tasks and tasks call one or more modules.**

At the end of a play the actions (tasks) in the handler are executed if they were called upon or triggered by tasks.

Here is an example of an Ansible playbook which contains just one play.  Note that it has to start with three dash (-) signs!

  −−−
  −name:  My First Play
    hosts:  webservers
    tasks:
    −name: ensure apache is at the latest version
      package:   
      name=httpd state=latest
    −name: write the apache config file
      copy:
        src=/srv/httpd.conf dest=/etc/httpd.conf
    notify:
      −restart apache
    −name: ensure apache is running (and enable it at boot)
      service:
        name=httpd
        state=started
        enabled=yes
    handlers:
    −name: restart apache
        service:
          name=httpd
          state=restarted

As you can see, playbooks are almost self explanatory.  The file starts with the name of the play and the hosts or inventory group to which to apply the play. Next, it lists all tasks to be performed. The last part contains the handlers.

Plays, like tasks, run in the order specified in the playbook: top to bottom. Each tasks is given a name and followed by one or more modules that’s doing the real ”work".
An Ansible playbook is run via the command `ansible-playbook <options> playbook-name.yml`.

Read this https://www.ansible.com/blog/getting-started-writing-your-first-playbook[text] and be sure you know what a playbook is. Otherise "Google is your friend"

* Write your first playbook named playbook.yml containing:
** one play with name "Play1"
** as target the host group "nodes"
** One task named "Ping" using the ping module

    ---
    - name: Play1
      hosts: nodes
      tasks:
      - name: Ping
        ping:

* Extend your playbook with another, play Play2 which installs nginx on the host group nodes

  [vagrant@master ~/ansible]$ bat playbook.yml
    1   │ ---
    2   │ - name: Play1
    3   │   hosts: nodes
    4   │   tasks:
    5   │   - name: Ping
    6   │     ping:
    7   │
    8   │ - name: Play2
    9   │   hosts: nodes
    10  │   become: yes
    11  │   tasks:
    12  │   - name: Install nginx
    13  │     apt:
    14  │       name: nginx
    15  │       update_cache: yes
    16  │       state: present
    17  │   - name: Start service nginx, if not started
    18  │     service:
    19  │       name: nginx
    20  │       state: started
  [vagrant@master ~/ansible]$

== Sources
* https://www.ansible.com/quick-start-video
* https://docs.ansible.com/ansible/playbooks.html
* https://www.ansible.com/webinars-training
* https://serversforhackers.com/an-ansible-tutorial